###############################################################################
# Created by write_sdc
# Tue Jun  4 09:40:29 2024
###############################################################################
current_design seven_segment_seconds
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name CLK -period 62.5000 [get_ports {clk}]
set_propagated_clock [get_clocks {CLK}]
group_path -name reg2reg\
    -from [list [get_cells {_374_}]\
           [get_cells {_375_}]\
           [get_cells {_376_}]\
           [get_cells {_377_}]\
           [get_cells {_378_}]\
           [get_cells {_379_}]\
           [get_cells {_380_}]\
           [get_cells {_381_}]\
           [get_cells {_382_}]\
           [get_cells {_383_}]\
           [get_cells {_384_}]\
           [get_cells {_385_}]\
           [get_cells {_386_}]\
           [get_cells {_387_}]\
           [get_cells {_388_}]\
           [get_cells {_389_}]\
           [get_cells {_390_}]\
           [get_cells {_391_}]\
           [get_cells {_392_}]\
           [get_cells {_393_}]\
           [get_cells {_394_}]\
           [get_cells {_395_}]\
           [get_cells {_396_}]\
           [get_cells {_397_}]\
           [get_cells {_398_}]\
           [get_cells {_399_}]\
           [get_cells {_400_}]\
           [get_cells {_401_}]\
           [get_cells {_402_}]\
           [get_cells {_403_}]\
           [get_cells {_404_}]\
           [get_cells {_405_}]\
           [get_cells {_406_}]\
           [get_cells {_407_}]\
           [get_cells {_408_}]\
           [get_cells {_409_}]\
           [get_cells {_410_}]\
           [get_cells {_411_}]\
           [get_cells {_412_}]\
           [get_cells {_413_}]\
           [get_cells {_414_}]\
           [get_cells {_415_}]\
           [get_cells {_416_}]\
           [get_cells {_417_}]\
           [get_cells {_418_}]\
           [get_cells {_419_}]\
           [get_cells {_420_}]\
           [get_cells {_421_}]\
           [get_cells {_422_}]\
           [get_cells {_423_}]\
           [get_cells {_424_}]\
           [get_cells {_425_}]]\
    -to [list [get_cells {_374_}]\
           [get_cells {_375_}]\
           [get_cells {_376_}]\
           [get_cells {_377_}]\
           [get_cells {_378_}]\
           [get_cells {_379_}]\
           [get_cells {_380_}]\
           [get_cells {_381_}]\
           [get_cells {_382_}]\
           [get_cells {_383_}]\
           [get_cells {_384_}]\
           [get_cells {_385_}]\
           [get_cells {_386_}]\
           [get_cells {_387_}]\
           [get_cells {_388_}]\
           [get_cells {_389_}]\
           [get_cells {_390_}]\
           [get_cells {_391_}]\
           [get_cells {_392_}]\
           [get_cells {_393_}]\
           [get_cells {_394_}]\
           [get_cells {_395_}]\
           [get_cells {_396_}]\
           [get_cells {_397_}]\
           [get_cells {_398_}]\
           [get_cells {_399_}]\
           [get_cells {_400_}]\
           [get_cells {_401_}]\
           [get_cells {_402_}]\
           [get_cells {_403_}]\
           [get_cells {_404_}]\
           [get_cells {_405_}]\
           [get_cells {_406_}]\
           [get_cells {_407_}]\
           [get_cells {_408_}]\
           [get_cells {_409_}]\
           [get_cells {_410_}]\
           [get_cells {_411_}]\
           [get_cells {_412_}]\
           [get_cells {_413_}]\
           [get_cells {_414_}]\
           [get_cells {_415_}]\
           [get_cells {_416_}]\
           [get_cells {_417_}]\
           [get_cells {_418_}]\
           [get_cells {_419_}]\
           [get_cells {_420_}]\
           [get_cells {_421_}]\
           [get_cells {_422_}]\
           [get_cells {_423_}]\
           [get_cells {_424_}]\
           [get_cells {_425_}]]
group_path -name reg2out\
    -from [list [get_cells {_374_}]\
           [get_cells {_375_}]\
           [get_cells {_376_}]\
           [get_cells {_377_}]\
           [get_cells {_378_}]\
           [get_cells {_379_}]\
           [get_cells {_380_}]\
           [get_cells {_381_}]\
           [get_cells {_382_}]\
           [get_cells {_383_}]\
           [get_cells {_384_}]\
           [get_cells {_385_}]\
           [get_cells {_386_}]\
           [get_cells {_387_}]\
           [get_cells {_388_}]\
           [get_cells {_389_}]\
           [get_cells {_390_}]\
           [get_cells {_391_}]\
           [get_cells {_392_}]\
           [get_cells {_393_}]\
           [get_cells {_394_}]\
           [get_cells {_395_}]\
           [get_cells {_396_}]\
           [get_cells {_397_}]\
           [get_cells {_398_}]\
           [get_cells {_399_}]\
           [get_cells {_400_}]\
           [get_cells {_401_}]\
           [get_cells {_402_}]\
           [get_cells {_403_}]\
           [get_cells {_404_}]\
           [get_cells {_405_}]\
           [get_cells {_406_}]\
           [get_cells {_407_}]\
           [get_cells {_408_}]\
           [get_cells {_409_}]\
           [get_cells {_410_}]\
           [get_cells {_411_}]\
           [get_cells {_412_}]\
           [get_cells {_413_}]\
           [get_cells {_414_}]\
           [get_cells {_415_}]\
           [get_cells {_416_}]\
           [get_cells {_417_}]\
           [get_cells {_418_}]\
           [get_cells {_419_}]\
           [get_cells {_420_}]\
           [get_cells {_421_}]\
           [get_cells {_422_}]\
           [get_cells {_423_}]\
           [get_cells {_424_}]\
           [get_cells {_425_}]]\
    -to [list [get_ports {VDD}]\
           [get_ports {VSS}]\
           [get_ports {led_out[0]}]\
           [get_ports {led_out[1]}]\
           [get_ports {led_out[2]}]\
           [get_ports {led_out[3]}]\
           [get_ports {led_out[4]}]\
           [get_ports {led_out[5]}]\
           [get_ports {led_out[6]}]]
group_path -name in2reg\
    -from [list [get_ports {VDD}]\
           [get_ports {VSS}]\
           [get_ports {clk}]\
           [get_ports {compare_in[0]}]\
           [get_ports {compare_in[10]}]\
           [get_ports {compare_in[11]}]\
           [get_ports {compare_in[12]}]\
           [get_ports {compare_in[13]}]\
           [get_ports {compare_in[14]}]\
           [get_ports {compare_in[15]}]\
           [get_ports {compare_in[16]}]\
           [get_ports {compare_in[17]}]\
           [get_ports {compare_in[18]}]\
           [get_ports {compare_in[19]}]\
           [get_ports {compare_in[1]}]\
           [get_ports {compare_in[20]}]\
           [get_ports {compare_in[21]}]\
           [get_ports {compare_in[22]}]\
           [get_ports {compare_in[23]}]\
           [get_ports {compare_in[2]}]\
           [get_ports {compare_in[3]}]\
           [get_ports {compare_in[4]}]\
           [get_ports {compare_in[5]}]\
           [get_ports {compare_in[6]}]\
           [get_ports {compare_in[7]}]\
           [get_ports {compare_in[8]}]\
           [get_ports {compare_in[9]}]\
           [get_ports {reset}]\
           [get_ports {update_compare}]]\
    -to [list [get_cells {_374_}]\
           [get_cells {_375_}]\
           [get_cells {_376_}]\
           [get_cells {_377_}]\
           [get_cells {_378_}]\
           [get_cells {_379_}]\
           [get_cells {_380_}]\
           [get_cells {_381_}]\
           [get_cells {_382_}]\
           [get_cells {_383_}]\
           [get_cells {_384_}]\
           [get_cells {_385_}]\
           [get_cells {_386_}]\
           [get_cells {_387_}]\
           [get_cells {_388_}]\
           [get_cells {_389_}]\
           [get_cells {_390_}]\
           [get_cells {_391_}]\
           [get_cells {_392_}]\
           [get_cells {_393_}]\
           [get_cells {_394_}]\
           [get_cells {_395_}]\
           [get_cells {_396_}]\
           [get_cells {_397_}]\
           [get_cells {_398_}]\
           [get_cells {_399_}]\
           [get_cells {_400_}]\
           [get_cells {_401_}]\
           [get_cells {_402_}]\
           [get_cells {_403_}]\
           [get_cells {_404_}]\
           [get_cells {_405_}]\
           [get_cells {_406_}]\
           [get_cells {_407_}]\
           [get_cells {_408_}]\
           [get_cells {_409_}]\
           [get_cells {_410_}]\
           [get_cells {_411_}]\
           [get_cells {_412_}]\
           [get_cells {_413_}]\
           [get_cells {_414_}]\
           [get_cells {_415_}]\
           [get_cells {_416_}]\
           [get_cells {_417_}]\
           [get_cells {_418_}]\
           [get_cells {_419_}]\
           [get_cells {_420_}]\
           [get_cells {_421_}]\
           [get_cells {_422_}]\
           [get_cells {_423_}]\
           [get_cells {_424_}]\
           [get_cells {_425_}]]
group_path -name in2out\
    -from [list [get_ports {VDD}]\
           [get_ports {VSS}]\
           [get_ports {clk}]\
           [get_ports {compare_in[0]}]\
           [get_ports {compare_in[10]}]\
           [get_ports {compare_in[11]}]\
           [get_ports {compare_in[12]}]\
           [get_ports {compare_in[13]}]\
           [get_ports {compare_in[14]}]\
           [get_ports {compare_in[15]}]\
           [get_ports {compare_in[16]}]\
           [get_ports {compare_in[17]}]\
           [get_ports {compare_in[18]}]\
           [get_ports {compare_in[19]}]\
           [get_ports {compare_in[1]}]\
           [get_ports {compare_in[20]}]\
           [get_ports {compare_in[21]}]\
           [get_ports {compare_in[22]}]\
           [get_ports {compare_in[23]}]\
           [get_ports {compare_in[2]}]\
           [get_ports {compare_in[3]}]\
           [get_ports {compare_in[4]}]\
           [get_ports {compare_in[5]}]\
           [get_ports {compare_in[6]}]\
           [get_ports {compare_in[7]}]\
           [get_ports {compare_in[8]}]\
           [get_ports {compare_in[9]}]\
           [get_ports {reset}]\
           [get_ports {update_compare}]]\
    -to [list [get_ports {VDD}]\
           [get_ports {VSS}]\
           [get_ports {led_out[0]}]\
           [get_ports {led_out[1]}]\
           [get_ports {led_out[2]}]\
           [get_ports {led_out[3]}]\
           [get_ports {led_out[4]}]\
           [get_ports {led_out[5]}]\
           [get_ports {led_out[6]}]]
set_false_path\
    -from [list [get_ports {VDD}]\
           [get_ports {VSS}]\
           [get_ports {clk}]\
           [get_ports {compare_in[0]}]\
           [get_ports {compare_in[10]}]\
           [get_ports {compare_in[11]}]\
           [get_ports {compare_in[12]}]\
           [get_ports {compare_in[13]}]\
           [get_ports {compare_in[14]}]\
           [get_ports {compare_in[15]}]\
           [get_ports {compare_in[16]}]\
           [get_ports {compare_in[17]}]\
           [get_ports {compare_in[18]}]\
           [get_ports {compare_in[19]}]\
           [get_ports {compare_in[1]}]\
           [get_ports {compare_in[20]}]\
           [get_ports {compare_in[21]}]\
           [get_ports {compare_in[22]}]\
           [get_ports {compare_in[23]}]\
           [get_ports {compare_in[2]}]\
           [get_ports {compare_in[3]}]\
           [get_ports {compare_in[4]}]\
           [get_ports {compare_in[5]}]\
           [get_ports {compare_in[6]}]\
           [get_ports {compare_in[7]}]\
           [get_ports {compare_in[8]}]\
           [get_ports {compare_in[9]}]\
           [get_ports {reset}]\
           [get_ports {update_compare}]]\
    -to [list [get_cells {_374_}]\
           [get_cells {_375_}]\
           [get_cells {_376_}]\
           [get_cells {_377_}]\
           [get_cells {_378_}]\
           [get_cells {_379_}]\
           [get_cells {_380_}]\
           [get_cells {_381_}]\
           [get_cells {_382_}]\
           [get_cells {_383_}]\
           [get_cells {_384_}]\
           [get_cells {_385_}]\
           [get_cells {_386_}]\
           [get_cells {_387_}]\
           [get_cells {_388_}]\
           [get_cells {_389_}]\
           [get_cells {_390_}]\
           [get_cells {_391_}]\
           [get_cells {_392_}]\
           [get_cells {_393_}]\
           [get_cells {_394_}]\
           [get_cells {_395_}]\
           [get_cells {_396_}]\
           [get_cells {_397_}]\
           [get_cells {_398_}]\
           [get_cells {_399_}]\
           [get_cells {_400_}]\
           [get_cells {_401_}]\
           [get_cells {_402_}]\
           [get_cells {_403_}]\
           [get_cells {_404_}]\
           [get_cells {_405_}]\
           [get_cells {_406_}]\
           [get_cells {_407_}]\
           [get_cells {_408_}]\
           [get_cells {_409_}]\
           [get_cells {_410_}]\
           [get_cells {_411_}]\
           [get_cells {_412_}]\
           [get_cells {_413_}]\
           [get_cells {_414_}]\
           [get_cells {_415_}]\
           [get_cells {_416_}]\
           [get_cells {_417_}]\
           [get_cells {_418_}]\
           [get_cells {_419_}]\
           [get_cells {_420_}]\
           [get_cells {_421_}]\
           [get_cells {_422_}]\
           [get_cells {_423_}]\
           [get_cells {_424_}]\
           [get_cells {_425_}]]
set_false_path\
    -from [list [get_ports {VDD}]\
           [get_ports {VSS}]\
           [get_ports {clk}]\
           [get_ports {compare_in[0]}]\
           [get_ports {compare_in[10]}]\
           [get_ports {compare_in[11]}]\
           [get_ports {compare_in[12]}]\
           [get_ports {compare_in[13]}]\
           [get_ports {compare_in[14]}]\
           [get_ports {compare_in[15]}]\
           [get_ports {compare_in[16]}]\
           [get_ports {compare_in[17]}]\
           [get_ports {compare_in[18]}]\
           [get_ports {compare_in[19]}]\
           [get_ports {compare_in[1]}]\
           [get_ports {compare_in[20]}]\
           [get_ports {compare_in[21]}]\
           [get_ports {compare_in[22]}]\
           [get_ports {compare_in[23]}]\
           [get_ports {compare_in[2]}]\
           [get_ports {compare_in[3]}]\
           [get_ports {compare_in[4]}]\
           [get_ports {compare_in[5]}]\
           [get_ports {compare_in[6]}]\
           [get_ports {compare_in[7]}]\
           [get_ports {compare_in[8]}]\
           [get_ports {compare_in[9]}]\
           [get_ports {reset}]\
           [get_ports {update_compare}]\
           [get_cells {_374_}]\
           [get_cells {_375_}]\
           [get_cells {_376_}]\
           [get_cells {_377_}]\
           [get_cells {_378_}]\
           [get_cells {_379_}]\
           [get_cells {_380_}]\
           [get_cells {_381_}]\
           [get_cells {_382_}]\
           [get_cells {_383_}]\
           [get_cells {_384_}]\
           [get_cells {_385_}]\
           [get_cells {_386_}]\
           [get_cells {_387_}]\
           [get_cells {_388_}]\
           [get_cells {_389_}]\
           [get_cells {_390_}]\
           [get_cells {_391_}]\
           [get_cells {_392_}]\
           [get_cells {_393_}]\
           [get_cells {_394_}]\
           [get_cells {_395_}]\
           [get_cells {_396_}]\
           [get_cells {_397_}]\
           [get_cells {_398_}]\
           [get_cells {_399_}]\
           [get_cells {_400_}]\
           [get_cells {_401_}]\
           [get_cells {_402_}]\
           [get_cells {_403_}]\
           [get_cells {_404_}]\
           [get_cells {_405_}]\
           [get_cells {_406_}]\
           [get_cells {_407_}]\
           [get_cells {_408_}]\
           [get_cells {_409_}]\
           [get_cells {_410_}]\
           [get_cells {_411_}]\
           [get_cells {_412_}]\
           [get_cells {_413_}]\
           [get_cells {_414_}]\
           [get_cells {_415_}]\
           [get_cells {_416_}]\
           [get_cells {_417_}]\
           [get_cells {_418_}]\
           [get_cells {_419_}]\
           [get_cells {_420_}]\
           [get_cells {_421_}]\
           [get_cells {_422_}]\
           [get_cells {_423_}]\
           [get_cells {_424_}]\
           [get_cells {_425_}]]\
    -to [list [get_ports {VDD}]\
           [get_ports {VSS}]\
           [get_ports {led_out[0]}]\
           [get_ports {led_out[1]}]\
           [get_ports {led_out[2]}]\
           [get_ports {led_out[3]}]\
           [get_ports {led_out[4]}]\
           [get_ports {led_out[5]}]\
           [get_ports {led_out[6]}]]
###############################################################################
# Environment
###############################################################################
###############################################################################
# Design Rules
###############################################################################
