/* Generated by Yosys 0.40+25 (git sha1 171577f90, g++ 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

(* src = "../../verilog/seven_segment_seconds.v:74.1-97.10" *)
module seg7(counter, segments);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  (* src = "../../verilog/seven_segment_seconds.v:75.22-75.29" *)
  input [3:0] counter;
  wire [3:0] counter;
  (* src = "../../verilog/seven_segment_seconds.v:76.22-76.30" *)
  output [6:0] segments;
  wire [6:0] segments;
  sky130_fd_sc_hd__o21a_1 _12_ (
    .A1(counter[2]),
    .A2(counter[1]),
    .B1(counter[3]),
    .X(_00_)
  );
  sky130_fd_sc_hd__o21bai_1 _13_ (
    .A1(counter[0]),
    .A2(counter[2]),
    .B1_N(counter[3]),
    .Y(_01_)
  );
  sky130_fd_sc_hd__o21a_1 _14_ (
    .A1(counter[2]),
    .A2(counter[1]),
    .B1(counter[0]),
    .X(_02_)
  );
  sky130_fd_sc_hd__nor2_1 _15_ (
    .A(_01_),
    .B(_02_),
    .Y(_03_)
  );
  sky130_fd_sc_hd__nor2_1 _16_ (
    .A(_00_),
    .B(_03_),
    .Y(segments[0])
  );
  sky130_fd_sc_hd__nor2_1 _17_ (
    .A(counter[0]),
    .B(counter[1]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _18_ (
    .A(counter[2]),
    .SLEEP(counter[1]),
    .X(_05_)
  );
  sky130_fd_sc_hd__a21boi_0 _19_ (
    .A1(counter[0]),
    .A2(counter[1]),
    .B1_N(counter[2]),
    .Y(_06_)
  );
  sky130_fd_sc_hd__o21ai_0 _20_ (
    .A1(counter[0]),
    .A2(counter[1]),
    .B1(_06_),
    .Y(_07_)
  );
  sky130_fd_sc_hd__o21ba_1 _21_ (
    .A1(counter[3]),
    .A2(_07_),
    .B1_N(_00_),
    .X(segments[1])
  );
  sky130_fd_sc_hd__o21ai_0 _22_ (
    .A1(counter[2]),
    .A2(counter[1]),
    .B1(_01_),
    .Y(segments[2])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _23_ (
    .A(counter[1]),
    .SLEEP(counter[2]),
    .X(_08_)
  );
  sky130_fd_sc_hd__nor2_1 _24_ (
    .A(_01_),
    .B(_08_),
    .Y(_09_)
  );
  sky130_fd_sc_hd__a221oi_1 _25_ (
    .A1(counter[0]),
    .A2(counter[3]),
    .B1(_07_),
    .B2(_09_),
    .C1(_00_),
    .Y(segments[3])
  );
  sky130_fd_sc_hd__nor3_1 _26_ (
    .A(counter[0]),
    .B(_00_),
    .C(_05_),
    .Y(segments[4])
  );
  sky130_fd_sc_hd__nor3_1 _27_ (
    .A(counter[3]),
    .B(_04_),
    .C(_06_),
    .Y(_10_)
  );
  sky130_fd_sc_hd__nor2_1 _28_ (
    .A(_00_),
    .B(_10_),
    .Y(segments[5])
  );
  sky130_fd_sc_hd__nor3_1 _29_ (
    .A(counter[3]),
    .B(_06_),
    .C(_08_),
    .Y(_11_)
  );
  sky130_fd_sc_hd__nor2_1 _30_ (
    .A(_00_),
    .B(_11_),
    .Y(segments[6])
  );
endmodule

(* top =  1  *)
(* src = "../../verilog/seven_segment_seconds.v:3.1-60.10" *)
module seven_segment_seconds(clk, reset, compare_in, update_compare, led_out);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  (* src = "../../verilog/seven_segment_seconds.v:4.13-4.16" *)
  input clk;
  wire clk;
  (* src = "../../verilog/seven_segment_seconds.v:14.16-14.23" *)
  wire [23:0] compare;
  (* src = "../../verilog/seven_segment_seconds.v:6.23-6.33" *)
  input [23:0] compare_in;
  wire [23:0] compare_in;
  (* src = "../../verilog/seven_segment_seconds.v:13.15-13.20" *)
  wire [3:0] digit;
  (* src = "../../verilog/seven_segment_seconds.v:8.20-8.27" *)
  output [6:0] led_out;
  wire [6:0] led_out;
  (* src = "../../verilog/seven_segment_seconds.v:5.16-5.21" *)
  input reset;
  wire reset;
  (* src = "../../verilog/seven_segment_seconds.v:12.16-12.30" *)
  wire [23:0] second_counter;
  (* src = "../../verilog/seven_segment_seconds.v:7.16-7.30" *)
  input update_compare;
  wire update_compare;
  sky130_fd_sc_hd__clkinv_1 _187_ (
    .A(digit[0]),
    .Y(_052_)
  );
  sky130_fd_sc_hd__clkinv_1 _188_ (
    .A(second_counter[22]),
    .Y(_053_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _189_ (
    .A(update_compare),
    .SLEEP(reset),
    .X(_054_)
  );
  sky130_fd_sc_hd__nor2_1 _190_ (
    .A(compare[1]),
    .B(compare[0]),
    .Y(_055_)
  );
  sky130_fd_sc_hd__nor3_1 _191_ (
    .A(compare[2]),
    .B(compare[1]),
    .C(compare[0]),
    .Y(_056_)
  );
  sky130_fd_sc_hd__or4_1 _192_ (
    .A(compare[3]),
    .B(compare[2]),
    .C(compare[1]),
    .D(compare[0]),
    .X(_057_)
  );
  sky130_fd_sc_hd__nor2_1 _193_ (
    .A(compare[4]),
    .B(_057_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__nor3_1 _194_ (
    .A(compare[5]),
    .B(compare[4]),
    .C(_057_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__or4_1 _195_ (
    .A(compare[6]),
    .B(compare[5]),
    .C(compare[4]),
    .D(_057_),
    .X(_060_)
  );
  sky130_fd_sc_hd__nor2_1 _196_ (
    .A(compare[7]),
    .B(_060_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__nor3_1 _197_ (
    .A(compare[8]),
    .B(compare[7]),
    .C(_060_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__or4_1 _198_ (
    .A(compare[9]),
    .B(compare[8]),
    .C(compare[7]),
    .D(_060_),
    .X(_063_)
  );
  sky130_fd_sc_hd__nor2_1 _199_ (
    .A(compare[10]),
    .B(_063_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__nor3_1 _200_ (
    .A(compare[11]),
    .B(compare[10]),
    .C(_063_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__or4_1 _201_ (
    .A(compare[12]),
    .B(compare[11]),
    .C(compare[10]),
    .D(_063_),
    .X(_066_)
  );
  sky130_fd_sc_hd__nor2_1 _202_ (
    .A(compare[13]),
    .B(_066_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nor3_1 _203_ (
    .A(compare[14]),
    .B(compare[13]),
    .C(_066_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__or4_1 _204_ (
    .A(compare[15]),
    .B(compare[14]),
    .C(compare[13]),
    .D(_066_),
    .X(_069_)
  );
  sky130_fd_sc_hd__nor2_1 _205_ (
    .A(compare[16]),
    .B(_069_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__nor3_1 _206_ (
    .A(compare[17]),
    .B(compare[16]),
    .C(_069_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__or4_1 _207_ (
    .A(compare[18]),
    .B(compare[17]),
    .C(compare[16]),
    .D(_069_),
    .X(_072_)
  );
  sky130_fd_sc_hd__nor2_1 _208_ (
    .A(compare[19]),
    .B(_072_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__or4_1 _209_ (
    .A(compare[21]),
    .B(compare[20]),
    .C(compare[19]),
    .D(_072_),
    .X(_074_)
  );
  sky130_fd_sc_hd__o21ai_0 _210_ (
    .A1(compare[22]),
    .A2(_074_),
    .B1(compare[23]),
    .Y(_075_)
  );
  sky130_fd_sc_hd__xnor2_1 _211_ (
    .A(compare[22]),
    .B(_074_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__nand2_1 _212_ (
    .A(_053_),
    .B(_076_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__o31ai_1 _213_ (
    .A1(compare[20]),
    .A2(compare[19]),
    .A3(_072_),
    .B1(compare[21]),
    .Y(_078_)
  );
  sky130_fd_sc_hd__a21o_1 _214_ (
    .A1(_074_),
    .A2(_078_),
    .B1(second_counter[21]),
    .X(_079_)
  );
  sky130_fd_sc_hd__and3_1 _215_ (
    .A(second_counter[21]),
    .B(_074_),
    .C(_078_),
    .X(_080_)
  );
  sky130_fd_sc_hd__or3_1 _216_ (
    .A(compare[23]),
    .B(compare[22]),
    .C(_074_),
    .X(_081_)
  );
  sky130_fd_sc_hd__xnor2_1 _217_ (
    .A(compare[1]),
    .B(second_counter[1]),
    .Y(_082_)
  );
  sky130_fd_sc_hd__nand2b_1 _218_ (
    .A_N(compare[0]),
    .B(second_counter[0]),
    .Y(_083_)
  );
  sky130_fd_sc_hd__nand2b_1 _219_ (
    .A_N(second_counter[0]),
    .B(compare[0]),
    .Y(_084_)
  );
  sky130_fd_sc_hd__mux2i_1 _220_ (
    .A0(_083_),
    .A1(_084_),
    .S(_082_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__xnor3_1 _221_ (
    .A(compare[2]),
    .B(second_counter[2]),
    .C(_055_),
    .X(_086_)
  );
  sky130_fd_sc_hd__xnor3_1 _222_ (
    .A(compare[3]),
    .B(second_counter[3]),
    .C(_056_),
    .X(_087_)
  );
  sky130_fd_sc_hd__xor3_1 _223_ (
    .A(compare[4]),
    .B(second_counter[4]),
    .C(_057_),
    .X(_088_)
  );
  sky130_fd_sc_hd__and4_1 _224_ (
    .A(_085_),
    .B(_086_),
    .C(_087_),
    .D(_088_),
    .X(_089_)
  );
  sky130_fd_sc_hd__xnor3_1 _225_ (
    .A(compare[5]),
    .B(second_counter[5]),
    .C(_058_),
    .X(_090_)
  );
  sky130_fd_sc_hd__xnor3_1 _226_ (
    .A(compare[6]),
    .B(second_counter[6]),
    .C(_059_),
    .X(_091_)
  );
  sky130_fd_sc_hd__xor3_1 _227_ (
    .A(compare[7]),
    .B(second_counter[7]),
    .C(_060_),
    .X(_092_)
  );
  sky130_fd_sc_hd__nand4_1 _228_ (
    .A(_089_),
    .B(_090_),
    .C(_091_),
    .D(_092_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__xnor3_1 _229_ (
    .A(compare[8]),
    .B(second_counter[8]),
    .C(_061_),
    .X(_094_)
  );
  sky130_fd_sc_hd__xnor3_1 _230_ (
    .A(compare[9]),
    .B(second_counter[9]),
    .C(_062_),
    .X(_095_)
  );
  sky130_fd_sc_hd__xor3_1 _231_ (
    .A(compare[10]),
    .B(second_counter[10]),
    .C(_063_),
    .X(_096_)
  );
  sky130_fd_sc_hd__and4b_1 _232_ (
    .A_N(_093_),
    .B(_094_),
    .C(_095_),
    .D(_096_),
    .X(_097_)
  );
  sky130_fd_sc_hd__xnor3_1 _233_ (
    .A(compare[11]),
    .B(second_counter[11]),
    .C(_064_),
    .X(_098_)
  );
  sky130_fd_sc_hd__xnor3_1 _234_ (
    .A(compare[12]),
    .B(second_counter[12]),
    .C(_065_),
    .X(_099_)
  );
  sky130_fd_sc_hd__xor3_1 _235_ (
    .A(compare[13]),
    .B(second_counter[13]),
    .C(_066_),
    .X(_100_)
  );
  sky130_fd_sc_hd__nand4_1 _236_ (
    .A(_097_),
    .B(_098_),
    .C(_099_),
    .D(_100_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__xnor3_1 _237_ (
    .A(compare[14]),
    .B(second_counter[14]),
    .C(_067_),
    .X(_102_)
  );
  sky130_fd_sc_hd__xnor3_1 _238_ (
    .A(compare[15]),
    .B(second_counter[15]),
    .C(_068_),
    .X(_103_)
  );
  sky130_fd_sc_hd__xor3_1 _239_ (
    .A(compare[16]),
    .B(second_counter[16]),
    .C(_069_),
    .X(_104_)
  );
  sky130_fd_sc_hd__and4b_1 _240_ (
    .A_N(_101_),
    .B(_102_),
    .C(_103_),
    .D(_104_),
    .X(_105_)
  );
  sky130_fd_sc_hd__xnor3_1 _241_ (
    .A(compare[17]),
    .B(second_counter[17]),
    .C(_070_),
    .X(_106_)
  );
  sky130_fd_sc_hd__xnor3_1 _242_ (
    .A(compare[18]),
    .B(second_counter[18]),
    .C(_071_),
    .X(_107_)
  );
  sky130_fd_sc_hd__xor3_1 _243_ (
    .A(compare[19]),
    .B(second_counter[19]),
    .C(_072_),
    .X(_108_)
  );
  sky130_fd_sc_hd__nand4_1 _244_ (
    .A(_105_),
    .B(_106_),
    .C(_107_),
    .D(_108_),
    .Y(_109_)
  );
  sky130_fd_sc_hd__xnor3_1 _245_ (
    .A(compare[20]),
    .B(second_counter[20]),
    .C(_073_),
    .X(_110_)
  );
  sky130_fd_sc_hd__xnor2_1 _246_ (
    .A(second_counter[23]),
    .B(_075_),
    .Y(_111_)
  );
  sky130_fd_sc_hd__a211o_1 _247_ (
    .A1(_053_),
    .A2(_076_),
    .B1(_080_),
    .C1(_109_),
    .X(_112_)
  );
  sky130_fd_sc_hd__o2111ai_1 _248_ (
    .A1(_053_),
    .A2(_076_),
    .B1(_079_),
    .C1(_081_),
    .D1(_110_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__nor4bb_1 _249_ (
    .A(_080_),
    .B(_109_),
    .C_N(_081_),
    .D_N(_079_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__o21a_1 _250_ (
    .A1(_053_),
    .A2(_076_),
    .B1(_110_),
    .X(_115_)
  );
  sky130_fd_sc_hd__nand4b_1 _251_ (
    .A_N(_111_),
    .B(_114_),
    .C(_115_),
    .D(_077_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__nand2b_1 _252_ (
    .A_N(_054_),
    .B(_116_),
    .Y(_117_)
  );
  sky130_fd_sc_hd__nor2_1 _253_ (
    .A(second_counter[0]),
    .B(_117_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__xnor2_1 _254_ (
    .A(second_counter[0]),
    .B(second_counter[1]),
    .Y(_118_)
  );
  sky130_fd_sc_hd__nor2_1 _255_ (
    .A(_117_),
    .B(_118_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__a21oi_1 _256_ (
    .A1(second_counter[0]),
    .A2(second_counter[1]),
    .B1(second_counter[2]),
    .Y(_119_)
  );
  sky130_fd_sc_hd__and3_1 _257_ (
    .A(second_counter[0]),
    .B(second_counter[1]),
    .C(second_counter[2]),
    .X(_120_)
  );
  sky130_fd_sc_hd__nor3_1 _258_ (
    .A(_117_),
    .B(_119_),
    .C(_120_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__nor2_1 _259_ (
    .A(second_counter[3]),
    .B(_120_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__and2_0 _260_ (
    .A(second_counter[3]),
    .B(_120_),
    .X(_122_)
  );
  sky130_fd_sc_hd__nor3_1 _261_ (
    .A(_117_),
    .B(_121_),
    .C(_122_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__nor2_1 _262_ (
    .A(second_counter[4]),
    .B(_122_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__and3_1 _263_ (
    .A(second_counter[3]),
    .B(second_counter[4]),
    .C(_120_),
    .X(_124_)
  );
  sky130_fd_sc_hd__nor3_1 _264_ (
    .A(_117_),
    .B(_123_),
    .C(_124_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__xnor2_1 _265_ (
    .A(second_counter[5]),
    .B(_124_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__nor2_1 _266_ (
    .A(_117_),
    .B(_125_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__a21oi_1 _267_ (
    .A1(second_counter[5]),
    .A2(_124_),
    .B1(second_counter[6]),
    .Y(_126_)
  );
  sky130_fd_sc_hd__and3_1 _268_ (
    .A(second_counter[5]),
    .B(second_counter[6]),
    .C(_124_),
    .X(_127_)
  );
  sky130_fd_sc_hd__nor3_1 _269_ (
    .A(_117_),
    .B(_126_),
    .C(_127_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__nor2_1 _270_ (
    .A(second_counter[7]),
    .B(_127_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__and2_0 _271_ (
    .A(second_counter[7]),
    .B(_127_),
    .X(_129_)
  );
  sky130_fd_sc_hd__nor3_1 _272_ (
    .A(_117_),
    .B(_128_),
    .C(_129_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__nor2_1 _273_ (
    .A(second_counter[8]),
    .B(_129_),
    .Y(_130_)
  );
  sky130_fd_sc_hd__nand2_1 _274_ (
    .A(second_counter[8]),
    .B(_129_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__nor3b_1 _275_ (
    .A(_117_),
    .B(_130_),
    .C_N(_131_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__xor2_1 _276_ (
    .A(second_counter[9]),
    .B(_131_),
    .X(_132_)
  );
  sky130_fd_sc_hd__nor2_1 _277_ (
    .A(_117_),
    .B(_132_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__a31oi_1 _278_ (
    .A1(second_counter[9]),
    .A2(second_counter[8]),
    .A3(_129_),
    .B1(second_counter[10]),
    .Y(_133_)
  );
  sky130_fd_sc_hd__and4_1 _279_ (
    .A(second_counter[9]),
    .B(second_counter[8]),
    .C(second_counter[10]),
    .D(_129_),
    .X(_134_)
  );
  sky130_fd_sc_hd__nor3_1 _280_ (
    .A(_117_),
    .B(_133_),
    .C(_134_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__nor2_1 _281_ (
    .A(second_counter[11]),
    .B(_134_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__nand2_1 _282_ (
    .A(second_counter[11]),
    .B(_134_),
    .Y(_136_)
  );
  sky130_fd_sc_hd__nor3b_1 _283_ (
    .A(_117_),
    .B(_135_),
    .C_N(_136_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__xor2_1 _284_ (
    .A(second_counter[12]),
    .B(_136_),
    .X(_137_)
  );
  sky130_fd_sc_hd__nor2_1 _285_ (
    .A(_117_),
    .B(_137_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__a31oi_1 _286_ (
    .A1(second_counter[11]),
    .A2(second_counter[12]),
    .A3(_134_),
    .B1(second_counter[13]),
    .Y(_138_)
  );
  sky130_fd_sc_hd__and4_1 _287_ (
    .A(second_counter[11]),
    .B(second_counter[13]),
    .C(second_counter[12]),
    .D(_134_),
    .X(_139_)
  );
  sky130_fd_sc_hd__nor3_1 _288_ (
    .A(_117_),
    .B(_138_),
    .C(_139_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__nor2_1 _289_ (
    .A(second_counter[14]),
    .B(_139_),
    .Y(_140_)
  );
  sky130_fd_sc_hd__nand2_1 _290_ (
    .A(second_counter[14]),
    .B(_139_),
    .Y(_141_)
  );
  sky130_fd_sc_hd__nor3b_1 _291_ (
    .A(_117_),
    .B(_140_),
    .C_N(_141_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__xor2_1 _292_ (
    .A(second_counter[15]),
    .B(_141_),
    .X(_142_)
  );
  sky130_fd_sc_hd__nor2_1 _293_ (
    .A(_117_),
    .B(_142_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__a31oi_1 _294_ (
    .A1(second_counter[15]),
    .A2(second_counter[14]),
    .A3(_139_),
    .B1(second_counter[16]),
    .Y(_143_)
  );
  sky130_fd_sc_hd__and4_1 _295_ (
    .A(second_counter[15]),
    .B(second_counter[14]),
    .C(second_counter[16]),
    .D(_139_),
    .X(_144_)
  );
  sky130_fd_sc_hd__nor3_1 _296_ (
    .A(_117_),
    .B(_143_),
    .C(_144_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__nor2_1 _297_ (
    .A(second_counter[17]),
    .B(_144_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__nand2_1 _298_ (
    .A(second_counter[17]),
    .B(_144_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__nor3b_1 _299_ (
    .A(_117_),
    .B(_145_),
    .C_N(_146_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__xor2_1 _300_ (
    .A(second_counter[18]),
    .B(_146_),
    .X(_147_)
  );
  sky130_fd_sc_hd__nor2_1 _301_ (
    .A(_117_),
    .B(_147_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__a31oi_1 _302_ (
    .A1(second_counter[17]),
    .A2(second_counter[18]),
    .A3(_144_),
    .B1(second_counter[19]),
    .Y(_148_)
  );
  sky130_fd_sc_hd__and4_1 _303_ (
    .A(second_counter[17]),
    .B(second_counter[19]),
    .C(second_counter[18]),
    .D(_144_),
    .X(_149_)
  );
  sky130_fd_sc_hd__nor3_1 _304_ (
    .A(_117_),
    .B(_148_),
    .C(_149_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__xnor2_1 _305_ (
    .A(second_counter[20]),
    .B(_149_),
    .Y(_150_)
  );
  sky130_fd_sc_hd__nor2_1 _306_ (
    .A(_117_),
    .B(_150_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__a21oi_1 _307_ (
    .A1(second_counter[20]),
    .A2(_149_),
    .B1(second_counter[21]),
    .Y(_151_)
  );
  sky130_fd_sc_hd__and3_1 _308_ (
    .A(second_counter[21]),
    .B(second_counter[20]),
    .C(_149_),
    .X(_152_)
  );
  sky130_fd_sc_hd__nor3_1 _309_ (
    .A(_117_),
    .B(_151_),
    .C(_152_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nand2_1 _310_ (
    .A(second_counter[22]),
    .B(_152_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__xnor2_1 _311_ (
    .A(second_counter[22]),
    .B(_152_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__nor2_1 _312_ (
    .A(_117_),
    .B(_154_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__xor2_1 _313_ (
    .A(second_counter[23]),
    .B(_153_),
    .X(_155_)
  );
  sky130_fd_sc_hd__nor2_1 _314_ (
    .A(_117_),
    .B(_155_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__nor4_1 _315_ (
    .A(_052_),
    .B(_111_),
    .C(_112_),
    .D(_113_),
    .Y(_156_)
  );
  sky130_fd_sc_hd__a211oi_1 _316_ (
    .A1(_052_),
    .A2(_116_),
    .B1(_156_),
    .C1(_054_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__nor2_1 _317_ (
    .A(digit[2]),
    .B(digit[1]),
    .Y(_157_)
  );
  sky130_fd_sc_hd__xnor2_1 _318_ (
    .A(digit[1]),
    .B(_156_),
    .Y(_158_)
  );
  sky130_fd_sc_hd__a211oi_1 _319_ (
    .A1(digit[3]),
    .A2(_157_),
    .B1(_158_),
    .C1(_054_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__a21oi_1 _320_ (
    .A1(digit[1]),
    .A2(_156_),
    .B1(digit[2]),
    .Y(_159_)
  );
  sky130_fd_sc_hd__and2_0 _321_ (
    .A(digit[2]),
    .B(digit[1]),
    .X(_160_)
  );
  sky130_fd_sc_hd__a211oi_1 _322_ (
    .A1(_156_),
    .A2(_160_),
    .B1(_159_),
    .C1(_054_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__a21oi_1 _323_ (
    .A1(_156_),
    .A2(_160_),
    .B1(digit[3]),
    .Y(_161_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _324_ (
    .A(_157_),
    .SLEEP(_160_),
    .X(_162_)
  );
  sky130_fd_sc_hd__a311oi_1 _325_ (
    .A1(digit[3]),
    .A2(_156_),
    .A3(_162_),
    .B1(_161_),
    .C1(_054_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__mux2i_1 _326_ (
    .A0(compare[0]),
    .A1(compare_in[0]),
    .S(update_compare),
    .Y(_163_)
  );
  sky130_fd_sc_hd__nor2_1 _327_ (
    .A(reset),
    .B(_163_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__mux2i_1 _328_ (
    .A0(compare[1]),
    .A1(compare_in[1]),
    .S(update_compare),
    .Y(_164_)
  );
  sky130_fd_sc_hd__nor2_1 _329_ (
    .A(reset),
    .B(_164_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__mux2i_1 _330_ (
    .A0(compare[2]),
    .A1(compare_in[2]),
    .S(update_compare),
    .Y(_165_)
  );
  sky130_fd_sc_hd__nor2_1 _331_ (
    .A(reset),
    .B(_165_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__mux2i_1 _332_ (
    .A0(compare[3]),
    .A1(compare_in[3]),
    .S(update_compare),
    .Y(_166_)
  );
  sky130_fd_sc_hd__nor2_1 _333_ (
    .A(reset),
    .B(_166_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__mux2i_1 _334_ (
    .A0(compare[4]),
    .A1(compare_in[4]),
    .S(update_compare),
    .Y(_167_)
  );
  sky130_fd_sc_hd__nor2_1 _335_ (
    .A(reset),
    .B(_167_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__mux2i_1 _336_ (
    .A0(compare[5]),
    .A1(compare_in[5]),
    .S(update_compare),
    .Y(_168_)
  );
  sky130_fd_sc_hd__nor2_1 _337_ (
    .A(reset),
    .B(_168_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__mux2i_1 _338_ (
    .A0(compare[6]),
    .A1(compare_in[6]),
    .S(update_compare),
    .Y(_169_)
  );
  sky130_fd_sc_hd__nor2_1 _339_ (
    .A(reset),
    .B(_169_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__mux2i_1 _340_ (
    .A0(compare[7]),
    .A1(compare_in[7]),
    .S(update_compare),
    .Y(_170_)
  );
  sky130_fd_sc_hd__nor2_1 _341_ (
    .A(reset),
    .B(_170_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__mux2i_1 _342_ (
    .A0(compare[8]),
    .A1(compare_in[8]),
    .S(update_compare),
    .Y(_171_)
  );
  sky130_fd_sc_hd__nor2_1 _343_ (
    .A(reset),
    .B(_171_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__mux2i_1 _344_ (
    .A0(compare[9]),
    .A1(compare_in[9]),
    .S(update_compare),
    .Y(_172_)
  );
  sky130_fd_sc_hd__nor2_1 _345_ (
    .A(reset),
    .B(_172_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _346_ (
    .A(compare[10]),
    .SLEEP(update_compare),
    .X(_173_)
  );
  sky130_fd_sc_hd__a211o_1 _347_ (
    .A1(update_compare),
    .A2(compare_in[10]),
    .B1(reset),
    .C1(_173_),
    .X(_038_)
  );
  sky130_fd_sc_hd__mux2i_1 _348_ (
    .A0(compare[11]),
    .A1(compare_in[11]),
    .S(update_compare),
    .Y(_174_)
  );
  sky130_fd_sc_hd__nor2_1 _349_ (
    .A(reset),
    .B(_174_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__mux2i_1 _350_ (
    .A0(compare[12]),
    .A1(compare_in[12]),
    .S(update_compare),
    .Y(_175_)
  );
  sky130_fd_sc_hd__nor2_1 _351_ (
    .A(reset),
    .B(_175_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _352_ (
    .A(compare[13]),
    .SLEEP(update_compare),
    .X(_176_)
  );
  sky130_fd_sc_hd__a211o_1 _353_ (
    .A1(update_compare),
    .A2(compare_in[13]),
    .B1(reset),
    .C1(_176_),
    .X(_041_)
  );
  sky130_fd_sc_hd__mux2i_1 _354_ (
    .A0(compare[14]),
    .A1(compare_in[14]),
    .S(update_compare),
    .Y(_177_)
  );
  sky130_fd_sc_hd__nor2_1 _355_ (
    .A(reset),
    .B(_177_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__mux2i_1 _356_ (
    .A0(compare[15]),
    .A1(compare_in[15]),
    .S(update_compare),
    .Y(_178_)
  );
  sky130_fd_sc_hd__nor2_1 _357_ (
    .A(reset),
    .B(_178_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__mux2i_1 _358_ (
    .A0(compare[16]),
    .A1(compare_in[16]),
    .S(update_compare),
    .Y(_179_)
  );
  sky130_fd_sc_hd__nor2_1 _359_ (
    .A(reset),
    .B(_179_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__mux2i_1 _360_ (
    .A0(compare[17]),
    .A1(compare_in[17]),
    .S(update_compare),
    .Y(_180_)
  );
  sky130_fd_sc_hd__nor2_1 _361_ (
    .A(reset),
    .B(_180_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _362_ (
    .A(compare[18]),
    .SLEEP(update_compare),
    .X(_181_)
  );
  sky130_fd_sc_hd__a211o_1 _363_ (
    .A1(update_compare),
    .A2(compare_in[18]),
    .B1(reset),
    .C1(_181_),
    .X(_046_)
  );
  sky130_fd_sc_hd__mux2i_1 _364_ (
    .A0(compare[19]),
    .A1(compare_in[19]),
    .S(update_compare),
    .Y(_182_)
  );
  sky130_fd_sc_hd__nor2_1 _365_ (
    .A(reset),
    .B(_182_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _366_ (
    .A(compare[20]),
    .SLEEP(update_compare),
    .X(_183_)
  );
  sky130_fd_sc_hd__a211o_1 _367_ (
    .A1(update_compare),
    .A2(compare_in[20]),
    .B1(reset),
    .C1(_183_),
    .X(_048_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _368_ (
    .A(compare[21]),
    .SLEEP(update_compare),
    .X(_184_)
  );
  sky130_fd_sc_hd__a211o_1 _369_ (
    .A1(update_compare),
    .A2(compare_in[21]),
    .B1(reset),
    .C1(_184_),
    .X(_049_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _370_ (
    .A(compare[22]),
    .SLEEP(update_compare),
    .X(_185_)
  );
  sky130_fd_sc_hd__a211o_1 _371_ (
    .A1(update_compare),
    .A2(compare_in[22]),
    .B1(reset),
    .C1(_185_),
    .X(_050_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _372_ (
    .A(compare[23]),
    .SLEEP(update_compare),
    .X(_186_)
  );
  sky130_fd_sc_hd__a211o_1 _373_ (
    .A1(compare_in[23]),
    .A2(update_compare),
    .B1(reset),
    .C1(_186_),
    .X(_051_)
  );
  (* src = "../../verilog/seven_segment_seconds.v:28.5-55.8" *)
  sky130_fd_sc_hd__dfxtp_1 _374_ (
    .CLK(clk),
    .D(_000_),
    .Q(second_counter[0])
  );
  (* src = "../../verilog/seven_segment_seconds.v:28.5-55.8" *)
  sky130_fd_sc_hd__dfxtp_1 _375_ (
    .CLK(clk),
    .D(_001_),
    .Q(second_counter[1])
  );
  (* src = "../../verilog/seven_segment_seconds.v:28.5-55.8" *)
  sky130_fd_sc_hd__dfxtp_1 _376_ (
    .CLK(clk),
    .D(_002_),
    .Q(second_counter[2])
  );
  (* src = "../../verilog/seven_segment_seconds.v:28.5-55.8" *)
  sky130_fd_sc_hd__dfxtp_1 _377_ (
    .CLK(clk),
    .D(_003_),
    .Q(second_counter[3])
  );
  (* src = "../../verilog/seven_segment_seconds.v:28.5-55.8" *)
  sky130_fd_sc_hd__dfxtp_1 _378_ (
    .CLK(clk),
    .D(_004_),
    .Q(second_counter[4])
  );
  (* src = "../../verilog/seven_segment_seconds.v:28.5-55.8" *)
  sky130_fd_sc_hd__dfxtp_1 _379_ (
    .CLK(clk),
    .D(_005_),
    .Q(second_counter[5])
  );
  (* src = "../../verilog/seven_segment_seconds.v:28.5-55.8" *)
  sky130_fd_sc_hd__dfxtp_1 _380_ (
    .CLK(clk),
    .D(_006_),
    .Q(second_counter[6])
  );
  (* src = "../../verilog/seven_segment_seconds.v:28.5-55.8" *)
  sky130_fd_sc_hd__dfxtp_1 _381_ (
    .CLK(clk),
    .D(_007_),
    .Q(second_counter[7])
  );
  (* src = "../../verilog/seven_segment_seconds.v:28.5-55.8" *)
  sky130_fd_sc_hd__dfxtp_1 _382_ (
    .CLK(clk),
    .D(_008_),
    .Q(second_counter[8])
  );
  (* src = "../../verilog/seven_segment_seconds.v:28.5-55.8" *)
  sky130_fd_sc_hd__dfxtp_1 _383_ (
    .CLK(clk),
    .D(_009_),
    .Q(second_counter[9])
  );
  (* src = "../../verilog/seven_segment_seconds.v:28.5-55.8" *)
  sky130_fd_sc_hd__dfxtp_1 _384_ (
    .CLK(clk),
    .D(_010_),
    .Q(second_counter[10])
  );
  (* src = "../../verilog/seven_segment_seconds.v:28.5-55.8" *)
  sky130_fd_sc_hd__dfxtp_1 _385_ (
    .CLK(clk),
    .D(_011_),
    .Q(second_counter[11])
  );
  (* src = "../../verilog/seven_segment_seconds.v:28.5-55.8" *)
  sky130_fd_sc_hd__dfxtp_1 _386_ (
    .CLK(clk),
    .D(_012_),
    .Q(second_counter[12])
  );
  (* src = "../../verilog/seven_segment_seconds.v:28.5-55.8" *)
  sky130_fd_sc_hd__dfxtp_1 _387_ (
    .CLK(clk),
    .D(_013_),
    .Q(second_counter[13])
  );
  (* src = "../../verilog/seven_segment_seconds.v:28.5-55.8" *)
  sky130_fd_sc_hd__dfxtp_1 _388_ (
    .CLK(clk),
    .D(_014_),
    .Q(second_counter[14])
  );
  (* src = "../../verilog/seven_segment_seconds.v:28.5-55.8" *)
  sky130_fd_sc_hd__dfxtp_1 _389_ (
    .CLK(clk),
    .D(_015_),
    .Q(second_counter[15])
  );
  (* src = "../../verilog/seven_segment_seconds.v:28.5-55.8" *)
  sky130_fd_sc_hd__dfxtp_1 _390_ (
    .CLK(clk),
    .D(_016_),
    .Q(second_counter[16])
  );
  (* src = "../../verilog/seven_segment_seconds.v:28.5-55.8" *)
  sky130_fd_sc_hd__dfxtp_1 _391_ (
    .CLK(clk),
    .D(_017_),
    .Q(second_counter[17])
  );
  (* src = "../../verilog/seven_segment_seconds.v:28.5-55.8" *)
  sky130_fd_sc_hd__dfxtp_1 _392_ (
    .CLK(clk),
    .D(_018_),
    .Q(second_counter[18])
  );
  (* src = "../../verilog/seven_segment_seconds.v:28.5-55.8" *)
  sky130_fd_sc_hd__dfxtp_1 _393_ (
    .CLK(clk),
    .D(_019_),
    .Q(second_counter[19])
  );
  (* src = "../../verilog/seven_segment_seconds.v:28.5-55.8" *)
  sky130_fd_sc_hd__dfxtp_1 _394_ (
    .CLK(clk),
    .D(_020_),
    .Q(second_counter[20])
  );
  (* src = "../../verilog/seven_segment_seconds.v:28.5-55.8" *)
  sky130_fd_sc_hd__dfxtp_1 _395_ (
    .CLK(clk),
    .D(_021_),
    .Q(second_counter[21])
  );
  (* src = "../../verilog/seven_segment_seconds.v:28.5-55.8" *)
  sky130_fd_sc_hd__dfxtp_1 _396_ (
    .CLK(clk),
    .D(_022_),
    .Q(second_counter[22])
  );
  (* src = "../../verilog/seven_segment_seconds.v:28.5-55.8" *)
  sky130_fd_sc_hd__dfxtp_1 _397_ (
    .CLK(clk),
    .D(_023_),
    .Q(second_counter[23])
  );
  (* src = "../../verilog/seven_segment_seconds.v:28.5-55.8" *)
  sky130_fd_sc_hd__dfxtp_1 _398_ (
    .CLK(clk),
    .D(_024_),
    .Q(digit[0])
  );
  (* src = "../../verilog/seven_segment_seconds.v:28.5-55.8" *)
  sky130_fd_sc_hd__dfxtp_1 _399_ (
    .CLK(clk),
    .D(_025_),
    .Q(digit[1])
  );
  (* src = "../../verilog/seven_segment_seconds.v:28.5-55.8" *)
  sky130_fd_sc_hd__dfxtp_1 _400_ (
    .CLK(clk),
    .D(_026_),
    .Q(digit[2])
  );
  (* src = "../../verilog/seven_segment_seconds.v:28.5-55.8" *)
  sky130_fd_sc_hd__dfxtp_1 _401_ (
    .CLK(clk),
    .D(_027_),
    .Q(digit[3])
  );
  (* src = "../../verilog/seven_segment_seconds.v:28.5-55.8" *)
  sky130_fd_sc_hd__dfxtp_1 _402_ (
    .CLK(clk),
    .D(_028_),
    .Q(compare[0])
  );
  (* src = "../../verilog/seven_segment_seconds.v:28.5-55.8" *)
  sky130_fd_sc_hd__dfxtp_1 _403_ (
    .CLK(clk),
    .D(_029_),
    .Q(compare[1])
  );
  (* src = "../../verilog/seven_segment_seconds.v:28.5-55.8" *)
  sky130_fd_sc_hd__dfxtp_1 _404_ (
    .CLK(clk),
    .D(_030_),
    .Q(compare[2])
  );
  (* src = "../../verilog/seven_segment_seconds.v:28.5-55.8" *)
  sky130_fd_sc_hd__dfxtp_1 _405_ (
    .CLK(clk),
    .D(_031_),
    .Q(compare[3])
  );
  (* src = "../../verilog/seven_segment_seconds.v:28.5-55.8" *)
  sky130_fd_sc_hd__dfxtp_1 _406_ (
    .CLK(clk),
    .D(_032_),
    .Q(compare[4])
  );
  (* src = "../../verilog/seven_segment_seconds.v:28.5-55.8" *)
  sky130_fd_sc_hd__dfxtp_1 _407_ (
    .CLK(clk),
    .D(_033_),
    .Q(compare[5])
  );
  (* src = "../../verilog/seven_segment_seconds.v:28.5-55.8" *)
  sky130_fd_sc_hd__dfxtp_1 _408_ (
    .CLK(clk),
    .D(_034_),
    .Q(compare[6])
  );
  (* src = "../../verilog/seven_segment_seconds.v:28.5-55.8" *)
  sky130_fd_sc_hd__dfxtp_1 _409_ (
    .CLK(clk),
    .D(_035_),
    .Q(compare[7])
  );
  (* src = "../../verilog/seven_segment_seconds.v:28.5-55.8" *)
  sky130_fd_sc_hd__dfxtp_1 _410_ (
    .CLK(clk),
    .D(_036_),
    .Q(compare[8])
  );
  (* src = "../../verilog/seven_segment_seconds.v:28.5-55.8" *)
  sky130_fd_sc_hd__dfxtp_1 _411_ (
    .CLK(clk),
    .D(_037_),
    .Q(compare[9])
  );
  (* src = "../../verilog/seven_segment_seconds.v:28.5-55.8" *)
  sky130_fd_sc_hd__dfxtp_1 _412_ (
    .CLK(clk),
    .D(_038_),
    .Q(compare[10])
  );
  (* src = "../../verilog/seven_segment_seconds.v:28.5-55.8" *)
  sky130_fd_sc_hd__dfxtp_1 _413_ (
    .CLK(clk),
    .D(_039_),
    .Q(compare[11])
  );
  (* src = "../../verilog/seven_segment_seconds.v:28.5-55.8" *)
  sky130_fd_sc_hd__dfxtp_1 _414_ (
    .CLK(clk),
    .D(_040_),
    .Q(compare[12])
  );
  (* src = "../../verilog/seven_segment_seconds.v:28.5-55.8" *)
  sky130_fd_sc_hd__dfxtp_1 _415_ (
    .CLK(clk),
    .D(_041_),
    .Q(compare[13])
  );
  (* src = "../../verilog/seven_segment_seconds.v:28.5-55.8" *)
  sky130_fd_sc_hd__dfxtp_1 _416_ (
    .CLK(clk),
    .D(_042_),
    .Q(compare[14])
  );
  (* src = "../../verilog/seven_segment_seconds.v:28.5-55.8" *)
  sky130_fd_sc_hd__dfxtp_1 _417_ (
    .CLK(clk),
    .D(_043_),
    .Q(compare[15])
  );
  (* src = "../../verilog/seven_segment_seconds.v:28.5-55.8" *)
  sky130_fd_sc_hd__dfxtp_1 _418_ (
    .CLK(clk),
    .D(_044_),
    .Q(compare[16])
  );
  (* src = "../../verilog/seven_segment_seconds.v:28.5-55.8" *)
  sky130_fd_sc_hd__dfxtp_1 _419_ (
    .CLK(clk),
    .D(_045_),
    .Q(compare[17])
  );
  (* src = "../../verilog/seven_segment_seconds.v:28.5-55.8" *)
  sky130_fd_sc_hd__dfxtp_1 _420_ (
    .CLK(clk),
    .D(_046_),
    .Q(compare[18])
  );
  (* src = "../../verilog/seven_segment_seconds.v:28.5-55.8" *)
  sky130_fd_sc_hd__dfxtp_1 _421_ (
    .CLK(clk),
    .D(_047_),
    .Q(compare[19])
  );
  (* src = "../../verilog/seven_segment_seconds.v:28.5-55.8" *)
  sky130_fd_sc_hd__dfxtp_1 _422_ (
    .CLK(clk),
    .D(_048_),
    .Q(compare[20])
  );
  (* src = "../../verilog/seven_segment_seconds.v:28.5-55.8" *)
  sky130_fd_sc_hd__dfxtp_1 _423_ (
    .CLK(clk),
    .D(_049_),
    .Q(compare[21])
  );
  (* src = "../../verilog/seven_segment_seconds.v:28.5-55.8" *)
  sky130_fd_sc_hd__dfxtp_1 _424_ (
    .CLK(clk),
    .D(_050_),
    .Q(compare[22])
  );
  (* src = "../../verilog/seven_segment_seconds.v:28.5-55.8" *)
  sky130_fd_sc_hd__dfxtp_1 _425_ (
    .CLK(clk),
    .D(_051_),
    .Q(compare[23])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../verilog/seven_segment_seconds.v:58.10-58.51" *)
  seg7 seg7 (
    .counter(digit),
    .segments(led_out)
  );
endmodule
